backend:
  name: github
  repo: Parijat29/gatsby-travel-blog

publish_mode: editorial_workflow
media_folder: static/assets
public_folder: assets

site_url: https://mp-s-travelblog.netlify.app/
display_url: https://mp-s-travelblog.netlify.app/


collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    delete: true
    path: '{{slug}}/index'
    sortableFields: ['commit_date', 'title']
    editor:
      preview: false
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: itinerary, label: Itinerary, widget: "ckEditorwidget" }
      - { name: budget, label: Budget, widget: "ckEditorwidget" }
      - { name: body, label: Body, widget: markdown }